// lib/seed.ts
import type { Resident, ShiftRecord } from "@/types";

const now  = Date.now();
const day  = 86_400_000;
const hour = 3_600_000;

// Helper — produce YYYY-MM-DD for a timestamp
function toDateStr(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10);
}

// ── 4 residents ───────────────────────────────────────────────────────────────
export const SEED_RESIDENTS: Resident[] = [
  {
    id: "res1",
    name: "Dorothy Pemberton",
    dob: "1940-06-12",
    roomNumber: "4",
    admittedDate: "2023-09-15",
    currentCondition: "Well",
    supportWorker: "Alison Hart",
    notes: "Enjoys morning tea and the garden. Hard of hearing in left ear. Family visits on Sundays.",
  },
  {
    id: "res2",
    name: "Albert Hughes",
    dob: "1935-03-28",
    roomNumber: "7",
    admittedDate: "2024-01-10",
    currentCondition: "Improving",
    supportWorker: "James Whitfield",
    notes: "History of mild dementia. Responds well to music. Prefers routine.",
  },
  {
    id: "res3",
    name: "Margaret Lawson",
    dob: "1942-11-05",
    roomNumber: "11",
    admittedDate: "2023-11-20",
    currentCondition: "Unwell",
    supportWorker: "Alison Hart",
    notes: "Diabetic. Requires blood glucose check each morning. Mobility difficulties — uses walking frame.",
  },
  {
    id: "res4",
    name: "George Thornton",
    dob: "1938-08-19",
    roomNumber: "15",
    admittedDate: "2024-03-05",
    currentCondition: "Well",
    supportWorker: "James Whitfield",
    notes: "Very sociable. Enjoys card games and television. No dietary restrictions.",
  },
];

// ── Seed records — dates are dynamic so they stay recent and the date filter works ──
export const SEED_RECORDS: ShiftRecord[] = [
  {
    id: "rec1",
    residentId: "res1",
    residentName: "Dorothy Pemberton",
    staffName: "Alison Hart",
    shift: "Morning",
    date: toDateStr(now - day * 2),
    timestamp: now - day * 2 + hour * 9,
    conditionUpdate: "Well",
    observations: "Dorothy was in good spirits this morning. Ate a full breakfast and enjoyed her tea in the garden.",
    careProvided: "Personal care completed. Assisted with morning routine and dressing.",
    medicationTaken: true,
    incidents: "",
    tasksForNextShift: "Check that Dorothy's daughter confirmed her Sunday visit. Remind afternoon team about her 4pm eye drops.",
    trashed: false,
  },
  {
    id: "rec2",
    residentId: "res2",
    residentName: "Albert Hughes",
    staffName: "James Whitfield",
    shift: "Afternoon",
    date: toDateStr(now - day * 2),
    timestamp: now - day * 2 + hour * 15,
    conditionUpdate: "Improving",
    observations: "Albert was calmer than yesterday. Responded well to the music session after lunch. Ate most of his dinner.",
    careProvided: "Assisted with lunch and personal hygiene. Participated in group music activity.",
    medicationTaken: true,
    incidents: "",
    tasksForNextShift: "Ensure Albert has his comfort blanket before settling for the night. Play relaxing music if he seems unsettled.",
    trashed: false,
  },
  {
    id: "rec3",
    residentId: "res3",
    residentName: "Margaret Lawson",
    staffName: "Alison Hart",
    shift: "Morning",
    date: toDateStr(now - day),
    timestamp: now - day + hour * 8,
    conditionUpdate: "Unwell",
    observations: "Margaret complained of nausea this morning. Ate very little at breakfast. Blood glucose reading was 9.2 — slightly elevated.",
    careProvided: "Blood glucose check completed. Encouraged fluid intake. Personal care assisted.",
    medicationTaken: true,
    incidents: "Margaret felt dizzy when standing — assisted back to her chair safely. No falls.",
    tasksForNextShift: "Repeat blood glucose check at 2pm. If nausea continues, contact the GP. Monitor fluid intake closely.",
    trashed: false,
  },
  {
    id: "rec4",
    residentId: "res4",
    residentName: "George Thornton",
    staffName: "James Whitfield",
    shift: "Morning",
    date: toDateStr(now - day),
    timestamp: now - day + hour * 10,
    conditionUpdate: "Well",
    observations: "George was cheerful and chatty. Joined the morning group activity and was very engaged.",
    careProvided: "Morning routine completed independently. Supervised card game session.",
    medicationTaken: true,
    incidents: "",
    tasksForNextShift: "George mentioned he would like to call his son this evening — please assist him with the phone after dinner.",
    trashed: false,
  },
  {
    id: "rec5",
    residentId: "res1",
    residentName: "Dorothy Pemberton",
    staffName: "James Whitfield",
    shift: "Afternoon",
    date: toDateStr(now - day),
    timestamp: now - day + hour * 14,
    conditionUpdate: "Well",
    observations: "Dorothy napped after lunch. Woke refreshed and asked to sit by the window. Appetite at dinner was good.",
    careProvided: "Assisted with repositioning and comfort. Administered 4pm eye drops.",
    medicationTaken: true,
    incidents: "",
    tasksForNextShift: "Eye drops again at 8am tomorrow. Daughter confirmed Sunday visit — note in her diary.",
    trashed: false,
  },
  {
    id: "rec6",
    residentId: "res3",
    residentName: "Margaret Lawson",
    staffName: "James Whitfield",
    shift: "Afternoon",
    date: toDateStr(now - day),
    timestamp: now - day + hour * 14 + 30 * 60000,
    conditionUpdate: "Unwell",
    observations: "Blood glucose at 2pm was 10.1. Nausea has not fully resolved. Margaret rested most of the afternoon.",
    careProvided: "Repeat blood glucose check. Ensured adequate hydration. Comfort care provided.",
    medicationTaken: true,
    incidents: "",
    tasksForNextShift: "Contact GP first thing tomorrow if blood glucose remains elevated. Continue monitoring fluid intake overnight.",
    trashed: false,
  },
];
